name: humancommunicator
favicon: null
layout_spectrum: 0.4473066271748394
typography_spectrum: 0.7043816638179123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.19140576478093863
  lightness: 0.4839876142796129
  saturation: 0.7883190009742975
  rhythmicContrast: 0.011636664159595966
purpose: []
